[build]
  publish = "public"
  functions = "netlify/functions"

# Har /api/... request Express function tak forward ho jayegi
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
